# Generated by Django 3.0 on 2020-03-28 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bin',
            fields=[
                ('bin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_items', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_fname', models.CharField(max_length=50)),
                ('customer_lname', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=30)),
                ('emp_lname', models.CharField(max_length=30)),
                ('emp_phone', models.CharField(max_length=30)),
                ('emp_email', models.CharField(max_length=50)),
                ('hire_date', models.CharField(max_length=30)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.department')),
            ],
        ),
        migrations.CreateModel(
            name='hazard',
            fields=[
                ('hazard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hazard_type', models.CharField(max_length=50)),
                ('hazard_rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.location')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('contract_limit', models.CharField(max_length=10)),
                ('qty_stock', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('hazard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.hazard')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=3)),
                ('customer_phone', models.CharField(max_length=12)),
                ('deliver_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.bin')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.customer')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.employee')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.job'),
        ),
        migrations.AddField(
            model_name='department',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.location'),
        ),
        migrations.AddField(
            model_name='bin',
            name='hazard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIT.hazard'),
        ),
    ]
