# Generated by Django 3.0 on 2020-04-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0002_auto_20200402_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_to_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_to_whse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
