# Generated by Django 3.0 on 2020-04-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0003_auto_20200403_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='published_date',
            field=models.CharField(default='', max_length=12),
        ),
    ]
