# Generated by Django 3.0 on 2020-04-04 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0004_auto_20200403_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='JIT.order_status'),
        ),
    ]
