# Generated by Django 3.0 on 2020-04-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0005_auto_20200403_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='JIT.order_status'),
        ),
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
