# Generated by Django 3.0 on 2020-04-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIT', '0006_auto_20200403_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
